openapi: 3.1.0
info:
  title: Currículo PDF API
  description: API que gera um currículo em PDF a partir dos dados fornecidos.
  version: 1.0.0
servers:
  - url: https://curriculo-pdf-api.onrender.com
    description: Servidor principal da API

paths:
  /export/canvas-pdf:
    post:
      operationId: exportarCurriculoPdf
      summary: Gera um currículo em PDF a partir de um template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                desiredTitle:
                  type: string
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                    phone:
                      type: string
                    linkedin:
                      type: string
                summary:
                  type: string
                experience:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      company:
                        type: string
                      startDate:
                        type: string
                      endDate:
                        type: string
                      bullets:
                        type: array
                        items:
                          type: string
                education:
                  type: array
                  items:
                    type: object
                    properties:
                      degree:
                        type: string
                      institution:
                        type: string
                      startDate:
                        type: string
                      endDate:
                        type: string
                skills:
                  type: array
                  items:
                    type: string
                certifications:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: PDF gerado com sucesso
          content:
            application/pdf:
              schema:
                type: string
                format: binary
