openapi: 3.1.0
info:
  title: Currículo PDF API
  description: API para geração de currículo em PDF a partir de dados estruturados.
  version: 1.0.0

servers:
  - url: https://cv-express.up.railway.app
    description: Servidor principal de geração de currículo PDF

paths:
  /export/canvas-pdf:
    post:
      operationId: exportCanvasPdf
      summary: Gera um currículo em PDF
      description: Recebe dados de currículo e retorna um arquivo PDF gerado com base em um template canvas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                desiredTitle:
                  type: string
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    phone:
                      type: string
                    linkedin:
                      type: string
                      format: uri
                summary:
                  type: string
                experience:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      company:
                        type: string
                      startDate:
                        type: string
                      endDate:
                        type: string
                      bullets:
                        type: array
                        items:
                          type: string
                education:
                  type: array
                  items:
                    type: object
                    properties:
                      degree:
                        type: string
                      institution:
                        type: string
                      startDate:
                        type: string
                      endDate:
                        type: string
                extras:
                  type: array
                  description: Seções adicionais como "Idiomas", "Certificações", "Skills" etc.
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        example: Idiomas
                      items:
                        type: array
                        items:
                          type: string
      responses:
        '200':
          description: PDF gerado com sucesso.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Requisição malformada ou dados incompletos.
        '500':
          description: Erro interno ao gerar o PDF.
