openapi: 3.1.0
info:
  title: Currículo PDF Generator API
  description: API para gerar um currículo em PDF com base em um modelo HTML com Handlebars.
  version: 1.0.0
servers:
  - url: https://curriculo-pdf-api.onrender.com
    description: Servidor principal (Render)
paths:
  /export/canvas-pdf:
    post:
      operationId: exportCurriculoPdf
      summary: Exporta currículo como PDF
      description: Gera e retorna um PDF com os dados do currículo preenchidos em um template HTML.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  description: Nome completo do candidato
                desiredTitle:
                  type: string
                  description: Cargo ou título profissional desejado
                contact:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    phone:
                      type: string
                    linkedin:
                      type: string
                      format: uri
                summary:
                  type: string
                  description: Resumo profissional
                experience:
                  type: array
                  description: Lista de experiências profissionais
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      company:
                        type: string
                      startDate:
                        type: string
                      endDate:
                        type: string
                      bullets:
                        type: array
                        items:
                          type: string
                education:
                  type: array
                  description: Lista de formações acadêmicas
                  items:
                    type: object
                    properties:
                      degree:
                        type: string
                      institution:
                        type: string
                      startDate:
                        type: string
                      endDate:
                        type: string
                skills:
                  type: array
                  items:
                    type: string
                certifications:
                  type: array
                  items:
                    type: string
              required:
                - fullName
                - desiredTitle
                - contact
                - summary
                - experience
                - education
      responses:
        '200':
          description: PDF gerado com sucesso
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Requisição inválida (dados ausentes ou mal formatados)
        '500':
          description: Erro interno ao gerar o PDF
